
services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  web1:
    restart: on-failure
    build: ./web
    depends_on:
      - redis
    hostname: web1
    volumes:
      - ./web:/usr/src/app
    ports:
      - '81:5000'
  web2:
    restart: on-failure
    build: ./web
    depends_on:
    - redis
    volumes:
      - ./web:/usr/src/app
    hostname: web2
    ports:
      - '82:5000'
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web1
    - web2


